### ISSUE TITLE
活该被政府封禁就你们这种傻逼我真是操你妈的你妈了个逼的把你妈吊起来操给

### ISSUE THREAD

**Issue by sjzsbgwb** [19920513/www#3]

**Comment by sjzsbgwb** [comment]
给你妈逼里塞核弹

**Comment by cmd1152** [comment]
![image](https://github.com/19920513/www/assets/109453324/3330bb50-3403-4f65-8db6-e4530d0b4bb5)

**Comment by sjzsbgwb** [comment]
# @19920513 我操死你妈个逼的，你mlgb的给你妈吊起来，操你这种人就活该他妈死妈
