### ISSUE TITLE
你以为edit和close可以去掉一个issues吗

### ISSUE THREAD

**Issue by cmd1152** [19920513/www#7]
点击Closed
![image](https://github.com/19920513/www/assets/109453324/8787c2d0-1add-47cd-b55a-9f0b614cfea9)
点击一个被傻逼关闭的issues
![image](https://github.com/19920513/www/assets/109453324/acb66124-5c7b-49d4-ae5b-0bfd3abf8977)
可以看见有显示 edit by 傻逼，点开
![image](https://github.com/19920513/www/assets/109453324/8539de33-beb1-453a-a376-2c977f73c5cc)
点击最开始的创建人的记录
![image](https://github.com/19920513/www/assets/109453324/e645eb06-1ae4-44e7-b470-a9d91f510311)
然后，就可以看见傻逼修改之前的了
![image](https://github.com/19920513/www/assets/109453324/1c45c64e-083e-4d30-a599-72ec482e1fcc)

**Comment by sjzsbgwb** [comment]
正道的光

**Comment by sjzsbgwb** [comment]
@19920513 我操死你妈个逼的，你mlgb的给你妈吊起来，操你这种人就活该他妈死妈
